DoAnCoSO/Controllers/CustomerController.cs
using DOANCOSO.Models;
using DOANCOSO.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Threading.Tasks;
namespace DOANCOSO.Controllers
{
    [RequireLogin]
    public class CustomerController : Controller
    {
        private readonly QuanlydichvuContext context;

        public CustomerController(QuanlydichvuContext _context)
        {
            context = _context;
        }


        public async Task<IActionResult> Index()
        {
            var customer = await context.KhachHangs.Include(p => p.MaLoaiKhachHangNavigation).ToListAsync();
            var typeCustomer = await context.LoaiKhachHangs.ToListAsync();
            ViewBag.TypeCustomer = new SelectList(typeCustomer, "MaLoaiKhachHang", "TenLoaiKhachHang");
            return View(customer);
        }

        public async Task<IActionResult> AddCustomer()
        {
            var typeCustomer = await context.LoaiKhachHangs.ToListAsync();
            ViewBag.TypeCustomer = new SelectList(typeCustomer, "MaLoaiKhachHang", "TenLoaiKhachHang");
            return View();

        }


        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> AddCustomer(KhachHang khachHang)
        {
            if (ModelState.IsValid)
            {
                context.KhachHangs.Add(khachHang);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập
            var typeCustomer = await context.LoaiKhachHangs.ToListAsync();
            ViewBag.TypeCustomer = new SelectList(typeCustomer, "MaLoaiKhachHang", "TenLoaiKhachHang");
            return View(khachHang);
        }

        [HttpPost]
        public async Task<IActionResult> AddTypeCustomer([FromBody] LoaiKhachHang loaiKhachHang)
        {
            if (ModelState.IsValid)
            {
                context.LoaiKhachHangs.Add(loaiKhachHang);
                await context.SaveChangesAsync();
                return Ok();
            }
            return BadRequest();
        }
        public async Task<IActionResult> EditCustomer(int id)
        {
            var khachHang = await context.KhachHangs.FindAsync(id);
            if (khachHang == null)
            {
                return NotFound();
            }

            var typeCustomer = await context.LoaiKhachHangs.ToListAsync();
            ViewBag.TypeCustomer = new SelectList(typeCustomer, "MaLoaiKhachHang", "TenLoaiKhachHang", khachHang.MaLoaiKhachHang);
            return View(khachHang);
        }
        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> EditCustomer(int id, KhachHang khachHang)
        {
            if (id != khachHang.MaKhachHang)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    context.Update(khachHang);
                    await context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KhachHangExists(khachHang.MaKhachHang))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            var typeCustomer = await context.LoaiKhachHangs.ToListAsync();
            ViewBag.TypeCustomer = new SelectList(typeCustomer, "MaLoaiKhachHang", "TenLoaiKhachHang", khachHang.MaLoaiKhachHang);
            return View(khachHang);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> DeleteCustomer(int id)
        {
            try
            {
                var khachHang = await context.KhachHangs.FindAsync(id);
                if (khachHang == null)
                {
                    return NotFound();
                }

                context.KhachHangs.Remove(khachHang);
                await context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            catch (DbUpdateException)
            {
                TempData["ErrorMessage"] = "Không thể xóa khách hàng vì khách hàng đang sử dụng một dịch vụ.";
                return RedirectToAction(nameof(Index));
            }
        }


        private bool KhachHangExists(int id)
        {
            return context.KhachHangs.Any(e => e.MaKhachHang == id);
        }

    }
}

DoAnCoSO/Views/Customer/AddCustomer.cshtml
@model DOANCOSO.Models.KhachHang;
@using Microsoft.AspNetCore.Mvc.Rendering;
@{
    ViewBag.Title = "ADD CUSTOMER";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm Khách Hàng</h2>

<form asp-controller="Customer" asp-action="AddCustomer" method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="TenKhachHang">Tên Khách</label>
        <input asp-for="TenKhachHang" class="form-control" id="form-control" />
        <span asp-validation-for="TenKhachHang" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SoDienThoai">Số Điện Thoại</label>
        <input asp-for="SoDienThoai" class="form-control" id="form-control" />
        <span asp-validation-for="SoDienThoai" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DiaChi">Địa Chỉ</label>
        <input asp-for="DiaChi" class="form-control" id="form-control" />
        <span asp-validation-for="DiaChi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MaLoaiKhachHang">Nhóm Khách Hàng</label>
        <select asp-for="MaLoaiKhachHang" class="form-control" asp-items="@(ViewBag.TypeCustomer as SelectList)"></select>
        <span asp-validation-for="MaLoaiKhachHang" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Add</button>
</form>

DoAnCoSO/Views/Customer/EditCustomer.cshtml
@model DOANCOSO.Models.KhachHang

@{
    ViewBag.Title = "Chỉnh sửa khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Chỉnh sửa khách hàng</h2>

<form asp-action="EditCustomer">
    <div class="form-group">
        <label asp-for="TenKhachHang" class="control-label"></label>
        <input asp-for="TenKhachHang" class="form-control" />
        <span asp-validation-for="TenKhachHang" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="SoDienThoai" class="control-label"></label>
        <input asp-for="SoDienThoai" class="form-control" />
        <span asp-validation-for="SoDienThoai" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="DiaChi" class="control-label"></label>
        <input asp-for="DiaChi" class="form-control" />
        <span asp-validation-for="DiaChi" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="MaLoaiKhachHang" class="control-label"></label>
        <select asp-for="MaLoaiKhachHang" class="form-control" asp-items="ViewBag.TypeCustomer"></select>
        <span asp-validation-for="MaLoaiKhachHang" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="hidden" asp-for="MaKhachHang" />
        <input type="submit" value="Lưu thay đổi" class="btn btn-primary" />
    </div>
</form>

<div>
    <a asp-action="Index">Trở về danh sách</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DoAnCoSO/Views/Customer/Index.cshtml
@model IEnumerable<DOANCOSO.Models.KhachHang>

@using Microsoft.AspNetCore.Mvc.Rendering;
@{
    ViewBag.Title = "Danh sách khách hàng";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Khách Hàng</h2>

<a class="nav-link text-dark btn btn-primary" asp-controller="Customer" asp-action="AddCustomer">Thêm Khách Hàng</a>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" style="background-color: #04B440;color: white;font-size: 13px;" data-bs-toggle="modal" data-bs-target="#AddTypeCustomer">
    Nhóm Khách
</button>
<table id="example" class="table table-striped">
    <thead>
        <tr>
            <th>Tên Khách</th>
            <th>Số Điện Thoại</th>
            <th>Địa Chỉ</th>
            <th>Nhóm Khách</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>@customer.TenKhachHang</td>
                <td>@customer.SoDienThoai</td>
                <td>@customer.DiaChi</td>
                <td>@customer.MaLoaiKhachHangNavigation.TenLoaiKhachHang</td>
                <td>
                    <a class="btn btn-info" asp-action="EditCustomer" asp-route-id="@customer.MaKhachHang">Edit</a> |
                    <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteModal" data-id="@customer.MaKhachHang" data-name="@customer.TenKhachHang">Delete</button>
                </td>
            </tr>
        }
    </tbody>
</table>

<!-- Delete Confirmation Modal -->
<div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel">Xóa Khách Hàng</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Bạn có chắc muốn xóa khách hàng: <strong id="customerName"></strong>?
            </div>
            <div class="modal-footer">
                <form id="deleteForm" method="post">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Error Modal -->
<div class="modal fade" id="errorModal" tabindex="-1" aria-labelledby="errorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="errorModalLabel">Error</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                @if (TempData["ErrorMessage"] != null)
                {
                    <div class="alert alert-danger">
                        @TempData["ErrorMessage"]
                    </div>
                }
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var errorMessage = '@TempData["ErrorMessage"]';
            if (errorMessage) {
                $('#errorModal').modal('show');
            }

            $('#deleteModal').on('show.bs.modal', function (event) {
                var button = $(event.relatedTarget);
                var customerId = button.data('id');
                var customerName = button.data('name');

                var modal = $(this);
                modal.find('#customerName').text(customerName);

                var form = modal.find('#deleteForm');
                form.attr('action', '/Customer/DeleteCustomer/' + customerId);
            });
        });
    </script>
}

<!-- Modal -->
<div class="modal fade" id="AddTypeCustomer" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Thêm Nhóm Khách</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="form-group">
                <label for="exampleFormControlSelect2">Danh Sách Nhóm Khách</label>
                <select class="form-control" id="exampleFormControlSelect2">
                    <option></option>
                    @foreach (var type in ViewBag.TypeCustomer as SelectList)
                    {
                        <option value="@type.Value">@type.Text</option>
                    }
                </select>
            </div>
            <div class="modal-body">
                <form id="addTypeCustomerForm">
                    <div class="mb-3">
                        <label for="input2" class="form-label">Tên Nhóm:</label>
                        <input class="form-control TenLoaiKhachHang" id="TenLoaiKhachHang" />
                        <span class="text-danger"></span>
                    </div>
                    <button type="submit" class="btn btn-primary">Thêm</button>
                </form>
            </div>
        </div>
    </div>
</div>